name = "EarthSciData"
uuid = "a293c155-435f-439d-9c11-a083b6b47337"
version = "0.14.0"
authors = ["EarthSciML Authors"]

[deps]
ConservativeRegridding = "8e50ac2c-eb48-49bc-a402-07c87b949343"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
EarthSciMLBase = "e53f1632-a13c-4728-9402-0c66d48804b0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[compat]
AllocCheck = "0.2"
ConservativeRegridding = "0.1"
DataInterpolations = "8"
DiffEqCallbacks = "4.3"
DocStringExtensions = "0.9.3"
DomainSets = "0.7.15"
Downloads = "1"
DynamicQuantities = "1"
EarthSciMLBase = "0.25"
Interpolations = "0.16"
JLD2 = "0.5"
LaTeXStrings = "1.3"
Latexify = "0.16.7"
ModelingToolkit = "11"
NCDatasets = "0.14"
OrdinaryDiffEqLowOrderRK = "1.2"
OrdinaryDiffEqSDIRK = "1.3"
OrdinaryDiffEqTsit5 = "1.1"
ProgressMeter = "1"
Proj = "1.8"
SciMLBase = "2.90"
Scratch = "1"
SymbolicIndexingInterface = "0.3.41, 0.4"
Symbolics = "7"
TestItemRunner = "1.1.0"
julia = "1.10"

[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
OrdinaryDiffEqSDIRK = "2d112036-d095-4a1e-ab9a-08536f3ecdbf"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner", "DomainSets", "LaTeXStrings", "OrdinaryDiffEqLowOrderRK", "OrdinaryDiffEqSDIRK", "OrdinaryDiffEqTsit5", "Random", "AllocCheck", "SymbolicIndexingInterface"]
